name: Deploy to APC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Astro CLI
        run: curl -sSL https://install.astronomer.io | sudo bash

      - name: Deploy to APC
        env:
          ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
        run: |
          astro deploy cmppik87t16d701ld32ftjblj --force
