name: Deploy to APC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Astro CLI
        run: curl -sSL https://install.astronomer.io | sudo bash

      - name: Deploy to APC
        env:
          ASTRONOMER_KEY_SECRET: ${{ secrets.ASTRONOMER_KEY_SECRET }}
        run: |
          mkdir -p ~/.astro
          printf 'context: demo-lab.aws.astronomer-demo.com\ncontexts:\n  demo-lab_aws_astronomer-demo_com:\n    domain: demo-lab.aws.astronomer-demo.com\n    token: %s\n    workspace: cmqiarxkc0008gz18vyojvlp4\n    last_used_workspace: cmqiarxkc0008gz18vyojvlp4\n' "$ASTRONOMER_KEY_SECRET" > ~/.astro/config.yaml
          astro deploy cmqicqsnp000ae0189ixus2u3 --force
