name: Deploy to APC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Astro CLI
        run: curl -sSL https://install.astronomer.io | sudo bash

      - name: Deploy to APC
        env:
          ASTRONOMER_KEY_SECRET: ${{ secrets.ASTRONOMER_KEY_SECRET }}
        run: |
          astro login demo-lab.aws.astronomer-demo.com -t "$ASTRONOMER_KEY_SECRET"
          astro deploy cmppik87t16d701ld32ftjblj --force
